---
layout: page
title: Blog
---

# Social Media in Psychological Sciences

Given the ever-transforming landscape of social media, it's difficult for those of us engaged in scientific psychological research to understand how best to use social media to connect with other professionals, disseminate our research, and learn about our peers' research.

## From Digital Marketer to Researcher

Prior to pursuing an education and career in Clinical Psychology and Clinical Research, I was a digital marketer on the pulse of emerging platforms, platform conventions, creating strategy and digital content, day in and day out. During this time, I developed brand strategy, served on a crisis communications team,  wrote press releases,  managed social media ads, and was even the lead script writer, script editor, and on-camera personality for the YouTube channel of an e-commerce company (becoming funnily enough somewhat of a microcelebrity in the Latvian e-commerce sphere). I left this field four year ago, and in this time, many of the commonplace platforms and approaches to social media have  become irrelevant. 

## Using X and LinkedIn

Take X for example, what used to host a thriving community of engaged PhDs and PhD students chatting about the rewards and struggles of the field, has quickly become a ghost town, where tumbleweed now weaves through sparse posts with links to recent manuscripts. Even LinkedIn, which is my current professional social media of choice, can be rife with sales-pitches and AI-slop. That said, LinkedIn can provide a great opportunity to stay abreast of unique expert insights, relevant events to attend, and accomplishments of peers.

One of my favorite recent LinkedIn follows is Dr. Rachel Wood, an expert on the Psychology of AI, who shares her professional perspectives on how AI is changing the landscape of how clients engage with AI to supplement (or replace) therapy, the dangers and benefits this poses, and how psychologists should approach client AI-use in their sessions. She posts frequently, replies to comments on her posts, and interacts with other peoples posts—all in intentional ways. 

Dr. Wood's approach differs vastly from the way many social-media-averse professionals use social media, which is often to 'advertise' their own work and achievements, sharing a conference photo or link to a publication, before exiting the platform until there is a new accomplishment to share. Her use of the platform demonstrates how social media should be used professionally—as a give-and-take, a way to build a meaningful network by sharing original thoughts, and building relationships with those in her network. 

Given how social media can over-expose us to the ills of the world, I very much understand and relate to the desire to be on social media as little as possible. But as researchers, need to move toward considering social media as another important avenue, beyond conferences and journals, to engage with others about our areas of interest and expertise. 

## Public Dissemination of Research

At the 2025 Association for Cognitive and Behavioral Therapies Convention in New Orleans, I attended an informative panel on science advocacy, which featured valuable insights on advancing psychological sciences across media and a variety of work settings. Panel speakers like Dr. Jonathan Abramowitz and Dr. Samuel Spencer underlined the need for psychologists to use media and social media to share evidence-bases information about the field with the general public and other professionals to meet them where they are. 

This public dissemination of information is especially important in a world where people get their information about psychology online, often through irreputable sources. I learned this firsthand during my undergraduate education, when I assisted with a study evaluating students' ability to discern from accurate and inaccurate information about OCD on TikTok (these students, who were all in Psychology 101, weren't able to tell the difference). 

In order to combat this misinformation crisis, psychologists need to be on the frontlines delivering accurate evidence-based insights about the field in accessible ways to mitigate the harm that is currently being caused by individuals and groups spreading false information about mental health (who range from being well-intentioned but misinformed to being unlicensed and profit-seeking).

## The Need for Edutainment

Perhaps as a field, we need figureheads, similar to those like 'Dr. Mike' on YouTube, who shares meaningful and accurate information about medicine to his 14.7 million subscribers in a way that captures their attention. I'm sure many experts in their field never imagined their future would consist of YouTube videos with titles like 'Doctor Reacts to My Strange Addiction' or 'Doctor Reacts to Deadliest Catch Injuries.' 

But in a world where many people are exhausted balancing the ever increasing demands of work, school, and family life—the average person likely lacks the energy, desire, or ability to read serious, dense, scholarly content in their free time. This doesn't mean they are shut off to learning, just that they may prefer to learn in a way that blends education with entertainment. 

While people may click on Dr. Mike's videos because of a reference to Marvel, while watching the video, they are likely to learn all kind of valuable and relevant information about injury prevention and how to mitigate injury once it occurs.

## How to Use Social Media for Science

In his book, How to Be A Modern Scientist, Jeff Leeks shares a number of suggestions as to how researchers can use  social media, such as: 

* Follow relevant people/journals
* Promote the work of other people (curating valuable content)
* Share work that you created
* Make online friends and meet them offline
* Add your commentary about other people's work
* Make YouTube shorts, TikToks, or Instagram Reels if you are open to using video
* Create infographics or images on  Tumblr or Instagram
* Using Twitter & LinkedIn if you prefer to share text-based posts

The ever-growing and ever-changing landscape of social media requires us to stay vigilant and curious as to how best to connect with research, researchers, and the broader public using social media. That said, the digital world can provide great opportunities for us to do all of these things—and some of these opportunities are only possible with social media. Let's put our fear and reservations aside—and get started, one post at a time. 